details:
  name: Minimum OA requirement
  description: To meet the ventilation requirements, the AHU must provide a certain amount of fresh air when the building is occupied. The ventilation requirements are determined at the design stage based on the zone occupancy and other parameters. The ventilation requirements are then translated into the outdoor-air damper opening, which is generally referred to as the minimum damper position to meet ventilation requirements, typically, the minimum damper position is between 10% and 20%. If the minimum damper position is greater than 20%, more outdoor-air may be entering the building than required, and significant additional heating or cooling may be occurring at the AHU to maintain the discharge-air temperature set point
  version: 1.0
  author: Roberto Chiosa
  email: roberto.chiosa@polito.it
  created_at: 2024-01-01

